// 随机选人任务没有真实的起止时间概念, 用一个足够长的占位时长避免被当成过期任务
const DRAW_TASK_DURATION = 30 * 24 * 3600 * 1000;

// 投票任务的默认与合法时长区间
const VOTE_DEFAULT_DURATION = 24 * 3600 * 1000;
const VOTE_MIN_DURATION = 60 * 1000;
const VOTE_MAX_DURATION = 30 * 24 * 3600 * 1000;

// 一次抽取/一场投票的规模上限, 防止单次请求写入过多数据
const DRAW_RANGE_MAX_LENGTH = 2000;
const VOTE_OPTION_MAX_LENGTH = 30;
const VOTE_OPTION_CONTENT_MAX_LENGTH = 100;
const VOTE_TITLE_MAX_LENGTH = 100;
const VOTE_VOTER_MAX_LENGTH = 2000;
const VOTE_MAX_CHOICES_LIMIT = 30;

// WebSocket 消息类型
const WS_MESSAGE_VOTE = "vote";
const WS_MESSAGE_VOTE_UPDATE = "vote_update";

module.exports = {
    DRAW_TASK_DURATION,
    VOTE_DEFAULT_DURATION,
    VOTE_MIN_DURATION,
    VOTE_MAX_DURATION,
    DRAW_RANGE_MAX_LENGTH,
    VOTE_OPTION_MAX_LENGTH,
    VOTE_OPTION_CONTENT_MAX_LENGTH,
    VOTE_TITLE_MAX_LENGTH,
    VOTE_VOTER_MAX_LENGTH,
    VOTE_MAX_CHOICES_LIMIT,
    WS_MESSAGE_VOTE,
    WS_MESSAGE_VOTE_UPDATE,
}
